# Generated by Django 2.1.8 on 2020-08-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KMusic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=20, verbose_name='歌曲')),
                ('singer_name', models.CharField(max_length=20, verbose_name='歌手')),
                ('time', models.CharField(max_length=10, verbose_name='时长')),
            ],
        ),
        migrations.CreateModel(
            name='QMusic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=20, verbose_name='歌曲')),
                ('singer_name', models.CharField(max_length=20, verbose_name='歌手')),
                ('time', models.CharField(max_length=10, verbose_name='时长')),
            ],
        ),
        migrations.CreateModel(
            name='WMusic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=20, verbose_name='歌曲')),
                ('singer_name', models.CharField(max_length=20, verbose_name='歌手')),
                ('time', models.CharField(max_length=10, verbose_name='时长')),
            ],
        ),
    ]
