# Generated by Django 2.1.8 on 2020-08-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kmusic',
            old_name='time',
            new_name='times',
        ),
        migrations.RenameField(
            model_name='qmusic',
            old_name='time',
            new_name='times',
        ),
        migrations.RenameField(
            model_name='wmusic',
            old_name='time',
            new_name='times',
        ),
        migrations.AlterField(
            model_name='kmusic',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qmusic',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wmusic',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
